// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.819
package buttons

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func DeleteDialog() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<dialog id=\"delete_dialog\"><article><header><button aria-label=\"Close\" rel=\"prev\" onclick=\"CloseDialog(&#39;delete_dialog&#39;)\"></button><p><strong>Delete</strong></p></header><fieldset id=\"table_set\"><legend>Choose table:</legend> <label><input type=\"radio\" name=\"table\" checked> users</label> <label><input type=\"radio\" name=\"table\"> broadcasts</label> <label><input type=\"radio\" name=\"table\"> videofiles</label> <details class=\"dropdown\"><summary>Other</summary><ul dir=\"rtl\"><li><a onclick=\"ShowDialog(&#39;delete_broadcasts_users_dialog&#39;); CloseDialog(&#39;delete_dialog&#39;);\">broadcasts_users</a></li><li><a onclick=\"ShowDialog(&#39;delete_broadcasts_files_dialog&#39;);CloseDialog(&#39;delete_dialog&#39;);\">broadcasts_files</a></li></ul></details></fieldset><input id=\"delete_id\" type=\"number\" min=\"0\"><footer><button class=\"secondary\" onclick=\"CloseDialog(&#39;delete_dialog&#39;)\">Cancel</button> <button onclick=\"Delete()\" id=\"dialog_delete_button\">Delete</button></footer><div id=\"delete-message\"></div></article></dialog><script src=\"http://localhost:1337/static/js/buttons/delete/delete.js\"></script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func DeleteBroadcastsFilesDialog() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<dialog id=\"delete_broadcasts_files_dialog\"><article><header><button onclick=\"CloseDialog(&#39;delete_broadcasts_files_dialog&#39;)\" class=\"close\" aria-label=\"Close\" rel=\"prev\"></button><p><strong><h2>Delete broadcasts_files</h2></strong></p></header><div style=\"text-align: center;\"><form id=\"add-form\"><input type=\"number\" name=\"broadcastid\" placeholder=\"Broadcast id\"> <input type=\"number\" name=\"fileid\" placeholder=\"File id\"> <button type=\"submit\">Add</button></form></div></article></dialog>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func DeleteBroadcastsUsersDialog() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var3 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var3 == nil {
			templ_7745c5c3_Var3 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<dialog id=\"delete_broadcasts_users_dialog\"><article><header><button onclick=\"CloseDialog(&#39;delete_broadcasts_users_dialog&#39;)\" class=\"close\" aria-label=\"Close\" rel=\"prev\"></button><p><strong><h2>Delete broadcasts_users</h2></strong></p></header><div style=\"text-align: center;\"><form id=\"add-form\"><input type=\"number\" name=\"broadcastid\" placeholder=\"Broadcast id\"> <input type=\"number\" name=\"userid\" placeholder=\"User id\"> <button type=\"submit\" hx-delete=\"http://localhost:1337/api/delete/broadcasts_users/\" hx-include=\"[name=&#39;broadcastid&#39;], [name=&#39;userid&#39;]\" hx-params=\"serialize\">Delete</button></form></div></article></dialog>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
