// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.819
package body

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/Cirqach/dms/cmd/templ/header"
	"github.com/Cirqach/dms/internal/database/models"
)

func Body(users []models.User, broadcasts []models.Broadcast, videofiles []models.Videofile) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>Document</title><link rel=\"stylesheet\" href=\"http://localhost:1488/static/css/pico.min.css\"><script src=\"https://unpkg.com/htmx.org@1.9.5\" integrity=\"sha384-xcuj3WpfgjlKF+FXhSQFQ0ZNr39ln+hwjN3npfM9VBnUskLolQAcN80McRIVOPuO\" crossorigin=\"anonymous\"></script></head><body><header class=\"container-fluid\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = header.Header(users, broadcasts, videofiles).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</header><main id=\"main\" class=\"container-fluid\"><h1 style=\"text-align: center;\">Select table</h1><div class=\"change-tables\"><table class=\"grid\"><tr><th>Users</th><th>Broadcast</th><th>Files</th><th>Broadcasts_files</th><th>Broadcasts_users</th></tr><tr><td><button onClick=\"ChangeTableName(&#39;Users&#39;)\" hx-get=\"/templ/tables/users\" hx-target=\"main\">Change</button></td><td><button onClick=\"ChangeTableName(&#39;Broadcasts&#39;)\" hx-get=\"/templ/tables/broadcasts\" hx-target=\"main\">Change</button></td><td><button onClick=\"ChangeTableName(&#39;Files&#39;)\" hx-get=\"/templ/tables/videofiles\" hx-target=\"main\">Change</button></td><td><button onClick=\"ChangeTableName(&#39;Broadcasts_files&#39;)\" hx-get=\"/templ/tables/broadcasts_files\" hx-target=\"main\">Change</button></td><td><button onClick=\"ChangeTableName(&#39;Broadcasts_users&#39;)\" hx-get=\"/templ/tables/broadcasts_users\" hx-target=\"main\">Change</button></td></tr></table><!-- Containers for dynamic options --><div id=\"broadcast-options\"></div><div id=\"user-options\"></div></div></main><footer></footer></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
