// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.819
package tables

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func ChangeTablePage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<summary>Change table</summary><ul dir=\"rtl\"><script>\n\t\tfunction ChangeTableName(name) {\n\t\t\tconst tablename = document.getElementById(\"tablename\");\n\t\t\ttablename.innerHTML = name;\n\t\t}\n\t</script><li><a onClick=\"ChangeTableName(&#39;Users&#39;)\" hx-get=\"/templ/tables/users\" hx-target=\"main\" id=\"tua\">Users</a></li><li><a onClick=\"ChangeTableName(&#39;Broadcasts&#39;)\" hx-get=\"/templ/tables/broadcasts\" hx-target=\"main\">Broadcasts</a></li><li><a onClick=\"ChangeTableName(&#39;Videofiles&#39;)\" hx-get=\"/templ/tables/videofiles\" hx-target=\"main\">Videofiles</a></li><li><a onClick=\"ChangeTableName(&#39;Broadcasts_files&#39;)\" hx-get=\"/templ/tables/broadcasts_files\" hx-target=\"main\">Broadcasts_files</a></li><li><a onClick=\"ChangeTableName(&#39;Broadcasts_users&#39;)\" hx-get=\"/templ/tables/broadcasts_users\" hx-target=\"main\">Broadcasts_users</a></li></ul>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
